### ISSUE TITLE
HELLO!

### ISSUE THREAD

**Issue by lowjiarong** [neuropsychology/Onboarding#3]
Hi there!

- **What's your name?** / **What are you currently doing?**

My name is Jia Rong. I am currently a final year student pursuing psychology in NTU, Singapore. I am currently doing my final year research project to conclude my undergraduate studies.

 **What would you like to do in the best possible future?**

In an ideal world, I would definitely be chilling at someplace with a nice scenery (probably somewhere high up) or hopefully lazing around at some beachside resort :)

 **What's your favourite dish or restaurant?** (@Tam-Pham and @zen-juen can go for MALA 🌶️ all day everyday; bonus points if you join us and laugh at @DominiqueMakowski for his spice intolerance)

Well I'm good with most cuisines especially when there are lots of meat or seafood though I do love my veggies as well. My top two cuisines will definitely be Chinese or Japanese, can't go wrong with it. (Well I'm definitely with @DominiqueMakowski on this one, no spice for me too so I guess we will be sweating it out)

**What's your hobbies outside of research?** (and don't say "work", "statistics" or "psychology")

Well, I do pursue some hands-on activities when I do have free time but nope I'm not gonna list them here :) Other than that, I do enjoy some Korean dramas on days when I am chilling.

**What's your go-to place to hang out?** (Are you like a @DominiqueMakowski who just wants to go drinkdrink party all day 🥳 )

Not a fan of alcohol here I must say. My hangout place always ends up at some food place somehow if not it will be at a cinema where you can take a break from the busy life for awhile. 

**Cats 🐱 or dogs 🐶?**

More of a dog person but sometimes cats are really interesting

**Drinks 🍻 (team @DominiqueMakowski) or food 🍔🍟 (team lame)?**

Team Lame🍔🍟

**Sport 🏅 or music 🎵?**

No sports but I miss exercising especially in the gym

**What's your favourite movie? (or genre)?** 

Definitely sci-fi or some triller

**What's your favourite city/country to be travelling around?** 🗺️

So far that I have been to, its definitely Taiwan cos people there are nice.

**If you weren't studying/pursuing a career in psychology, what would you be doing? (You can be absolutely creative with this and imagine a world with 0 restrictions)**

A designer of some sort I guess, probably some form of artist.

**Comment by zen-juen** [comment]
Hi @lowjiarong you are now part of team cool 🍔🍟  against team drunk 🍻 (@DominiqueMakowski) Welcome to GitHub!! Closing this 😄
