### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by elaineteo2000** [neuropsychology/Onboarding#4]
So for starters, let's create an issue to introduce yourself! This is informal and totally for fun so don't feel like you have to write us a CV 😉

*(PS: this will become public information, so don't spill out any secret or too embarassing anecdotes)* 😬

You can tell us anything you want about yourself, including answering the questions below. Best is to remove all of this pre-written text, and just leave the questions and your answers :relaxed:

----

- **What's your name?** (or more specifically, what do you want us to call you) 

my name is not very shorten-able, so you can just call me elaine/laine :")

- **What are you currently doing?** (e.g. studying/in a research position etc.)

studying (but not really)

- **What would you like to do in the best possible future?** (e.g. lying on the beach with some fancy cocktail 🍸)

star-gazing, snorkeling, swimming, and doing a ton of water rides in my own private beach hahaha

- **What's your favourite dish or restaurant?** (@Tam-Pham and @zen-juen can go for MALA 🌶️ all day everyday; bonus points if you join us and laugh at @DominiqueMakowski for his spice intolerance)

I don't have a favourite dish, but I love noodles!! so yes for mala I prefer to eat it with noodles instead of rice :")

- **What's your hobbies outside of research?** (and don't say "work", "statistics" or "psychology")

dancing, listening to music, swimming, couch-potatoing

- **What's your go-to place to hang out?** (Are you like a @DominiqueMakowski who just wants to go drinkdrink party all day 🥳 )

ideally, by the sea/river/lake (I like water bodies haha) or in someone's home. but in reality probably I always end up at orchard malls lol

- **Cats 🐱 or dogs 🐶?**

dogs!!

- **Drinks 🍻 (team @DominiqueMakowski) or food 🍔🍟 (team lame)?**

food all the way

- **Sport 🏅 or music 🎵?**

definitely music

- **What's your favourite movie? (or genre)?** 

I like any feel-good animated films (I love prince of egypt) :")

- **What's your favourite city/country to be travelling around?** 🗺️

japan, or anywhere in scandinavia!!

- **If you weren't studying/pursuing a career in psychology, what would you be doing? (You can be absolutely creative with this and imagine a world with 0 restrictions)**

part dancer, part film creative director, part writer

- **Anything else?**

hehe yay excited!!!

**Comment by DominiqueMakowski** [comment]
Hi @elaineteo2000 the noodle-lover 👋 Welcome to GitHub and to the team ☺️
