### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by ShreyaJolly** [neuropsychology/Onboarding#5]
- **What's your name?** (or more specifically, what do you want us to call you) 

Shreya Jolly.

- **What are you currently doing?** (e.g. studying/in a research position etc.)

I am currently a 3rd year biological science student studying biological sciences and business [minor].

- **What would you like to do in the best possible future?** (e.g. lying on the beach with some fancy cocktail 🍸)

Live like a kardashian!

- **What's your favourite dish or restaurant?** (@Tam-Pham and @zen-juen can go for MALA 🌶️ all day everyday; bonus points if you join us and laugh at @DominiqueMakowski for his spice intolerance)

Favourite dish - Mac and cheese
Favourite restaurant - cannot chose!

- **What's your hobbies outside of research?** (and don't say "work", "statistics" or "psychology")

- Art and craft, playing tennis.

- **What's your go-to place to hang out?** (Are you like a @DominiqueMakowski who just wants to go drinkdrink party all day 🥳 )

- Do not really have one!

- **Cats 🐱 or dogs 🐶?**

Dogs

- **Drinks 🍻 (team @DominiqueMakowski) or food 🍔🍟 (team lame)?**
Food! I do not drink...

- **Sport 🏅 or music 🎵?**

Sports.

- **What's your favourite movie? (or genre)?** 
Favourite genre - Thrillers and horror.

- **What's your favourite city/country to be travelling around?** 🗺️

Australia

- **If you weren't studying/pursuing a career in psychology, what would you be doing? (You can be absolutely creative with this and imagine a world with 0 restrictions)**

I would probably try becoming an artist.

- **Anything else?**

**Comment by DominiqueMakowski** [comment]
Hi @ShreyaJolly, congrats on your first issue and welcome aboard 🤗

**Comment by ShreyaJolly** [comment]
> Hi @ShreyaJolly, congrats on your first issue and welcome aboard 🤗

Thanks!!
